# pricing types
FOURIER = ["FOURIER", "Fourier", "fourier"]

# option types
CALL = "CALL"
PUT = "PUT"

# payoff types
VANILLA = "VANILLA"
TRUNCATED = "TRUNCATED"

# characteristic function direction
FORWARD_PROBLEM = "FORWARD_PROBLEM"
BACKWARD_PROBLEM = "BACKWARD_PROBLEM"

# filter types
FILTER_OFF = "FILTER_OFF"
FILTER_ON = "FILTER_ON"

# Gibbs filter type
EXPONENTIAL_FILTER = "EXPONENTIAL_FILTER"
PLANCK_TAPER_WINDOW = "PLANCK_TAPER_WINDOW"

# Hilbert transform
RIGHT_CONT_SIGN = "RIGHT_CONT_SIGN"
LEFT_CONT_SIGN = "LEFT_CONT_SIGN"
SYMMETRIC_SIGN = "SYMMETRIC_SIGN"
SINC_METHOD = "SINC_METHOD"

# LS flag
GUASSIAN_ELIM = "GUASSIAN_ELIM"
MIN_RESIDUAL = "MIN_RESIDUAL"
LNC_PRECONDITIONER = "LNC_PRECONDITIONER"

# methods
FENG_LINETSKY = "FENG_LINETSKY"
SPITZER = "SPITZER"

# izt methods
ABATE_WHITT = "ABATE_WHITT"
EULER_ON = "EULER_ON"
CAVERS = "CAVERS"
CAVERS_SUM = "CAVERS_SUM"
CAVERS_ACC_S = "CAVERS_ACC_S"
CAVERS_ACC_E = "CAVERS_ACC_E"
